### ISSUE TITLE
Create CONTRIBUTORS.md file for TSC

### ISSUE THREAD

**Issue by caniszczyk** [prestodb/tsc#3]
The charter specifies a CONTRIBUTORS file that the TOC

**Comment by brianwarner** [comment]
I just pushed a branch (https://github.com/prestodb/tsc/tree/add-draft-coc) containing a `CODE_OF_CONDUCT.md` file with the text of the Contributor Covenant v1.4.1.

Per the technical charter, this will be reviewed and voted upon by the TSC.  At that point, the PR can be landed and the DRAFT notice removed from the first line.

**Comment by brianwarner** [comment]
And guess who commented on the wrong issue ;-)  Deleting this comment and the prior one.

**Comment by brianwarner** [comment]
A first draft of the CONTRIBUTING.md file is in PR #10.  I also closed an automated bot-generated PR (#1) in favor of this one.

**Comment by brianwarner** [comment]
Closing out this issue, as the CONTRIBUTING.md file has been (re-)submitted as PR in the .github repo.
