### ISSUE TITLE
Elect TSC Chair

### ISSUE THREAD

**Issue by caniszczyk** [prestodb/tsc#5]
@nezihyigitbasi  has been volunteered.

**Comment by brianwarner** [comment]
Thanks!  This election should be the first item on the next TSC agenda.

**Comment by caniszczyk** [comment]
I believe this was done @brianwarner ?

**Comment by brianwarner** [comment]
Yes, that's correct. Nezih was elected in the [November 19th TSC meeting](https://github.com/prestodb/tsc/blob/master/meetings/2019-11-19.md) and this was merged into the README in #22. We can close this one.
