### ISSUE TITLE
Create CODE OF CONDUCT

### ISSUE THREAD

**Issue by caniszczyk** [prestodb/tsc#6]
We need to move off of the FB code of conduct

**Comment by brianwarner** [comment]
I just pushed a branch (https://github.com/prestodb/tsc/tree/add-draft-coc) containing a CODE_OF_CONDUCT.md file with the text of the Contributor Covenant v1.4.1.

Per the technical charter, this will be reviewed and voted upon by the TSC. At that point, the PR can be landed and the DRAFT notice removed from the first line.

**Comment by brianwarner** [comment]
This is now PR #11.  There was an automatic bot-created PR (#2), which I closed in favor of this one.

**Comment by brianwarner** [comment]
Replicating my comment in the PR, I think it probably makes sense to move this file into the .github repo once the text is approved.

**Comment by brianwarner** [comment]
Closing this because the PRs have been merged.
